#!/usr/bin/env bash
# Script that displays information about subdomains.

display_info() {
	dig "$1.$2" | grep -A1 'ANSWER SECTION:' | paste - - | awk -v sd="$1" '{print "The subdomain " sd " is a " $6 " record and points to " $7}'
}

if [ -n "$2" ]; then
	display_info "$2" "$1"
else
	display_info "www" "$1"
	display_info "lb-01" "$1"
	display_info "web-01" "$1"
	display_info "web-02" "$1"
fi

