#!/usr/bin/env bash
# Transfers a file from a client to a server

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -eq 4 ]; then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
else
	echo "Too many parameters provided."
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
